{% set name = "pyOlog" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c31051f9cd32fbba4f00acd4637c1344ad4facc3d8c165e1b8324486270ba7ef

build:
  number: 1
  noarch: python
  entry_points:
    - olog = pyOlog.cli:main
    - ologgui = pyOlog.gui:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - ipython
    - keyring
    - requests
    - six

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - pyOlog

about:
  home: https://github.com/NSLS-II/pyOlog
  license: MIT
  license_file: LICENSE.md
  summary: Python client library for OLog

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
