{% set name = "pyOlog" %}
{% set version = "4.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 51be7f995e6e30bc36926fb1a262c61a7b845f6aa22cf075ef94cdad099130b8

build:
  number: 0
  noarch: python
  entry_points:
    - olog = pyOlog.cli:main
    - ologgui = pyOlog.gui:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - ipython
    - keyring
    - requests
    - six

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - pyOlog

about:
  home: https://github.com/NSLS-II/pyOlog
  license: MIT
  license_file: LICENSE.md
  summary: Python client library for OLog

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
